# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Publish NPM on Version Changed

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run-script testEverything
        env:
          TEST_BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
          TEST_CHAT_ID: ${{ secrets.TEST_CHAT_ID }}
          TEST_BOT_USERNAME: ${{ secrets.TEST_BOT_USERNAME }}
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
